name: se-algo
channels:
  - defaults
  - apple
dependencies:
  - python=3.9
  - pip
  - tensorflow-deps==2.9.*
  - pip:
      - tensorflow-macos==2.9.*
      - tensorflow-metal==0.5.*
      - git+https://github.com/solen0id/sktime@mlstm-fcn-with-dilation#egg=sktime
      - scikit-learn
      - pandas
      - numba
      - matplotlib
      - ipykernel
      - jupyter
      - black
